apiVersion: v1
kind: Service

metadata:
  name: ocnference-api-service
  labels:
    app: conference-app
spec:
  # type: NodePort
  type: LoadBalancer
#  type: ClusterIP
  ports:
    - name: http-traffic
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: conference-api
