---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: conference-demo-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: conference-demo-service
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics-port
      path: "/actuator/prometheus"