---
#Force kubelet metrics on http
kubelet:
  enabled: true
  serviceMonitor:
    https: false

#Disable scrapping of master node components
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false