apiVersion: v1
kind: Service

metadata:
  name: conferenceapi
  labels:
    k8s-apps: http
spec:
  # type: NodePort
#  type: LoadBalancer
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
  selector:
    run: conferenceapi