apiVersion: v1
kind: Service
metadata:
  name: conference-demo-service
  labels:
    app: conference-demo-service
spec:
  type: LoadBalancer
  ports:
    - name: metrics-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: conference-demo-service
