#apiVersion: v1
#kind: Service
#
#metadata:
#  name: spring-prometheus-demo-service
#  labels:
#    app: spring-prometheus-demo
#spec:
#  # type: NodePort
##  type: LoadBalancer
#  type: ClusterIP
#  ports:
#    - name: http-traffic
#      protocol: TCP
#      port: 8080
#      targetPort: 8080
#  selector:
#    app: spring-prometheus-demo
