apiVersion: v1
kind: Service

metadata:
  name: conference-demo-service
  labels:
    app: conference-demo-service
spec:
  # type: NodePort
  type: LoadBalancer
#  type: ClusterIP
  ports:
    - name: metrics-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: conference-demo-service
